# Generated by Django 4.0.6 on 2022-08-04 03:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Institution',
            fields=[
                ('inst_code', models.CharField(max_length=9, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=16)),
                ('owner_name', models.CharField(max_length=50)),
                ('owner_uid', models.CharField(max_length=16)),
                ('street', models.CharField(max_length=20)),
                ('district', models.CharField(max_length=20)),
                ('state', models.CharField(max_length=20)),
                ('pincode', models.IntegerField()),
                ('email', models.CharField(max_length=30)),
                ('mobile', models.IntegerField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Organisation',
            fields=[
                ('org_code', models.CharField(max_length=9, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=16)),
                ('owner_name', models.CharField(max_length=50)),
                ('owner_uid', models.CharField(max_length=16)),
                ('street', models.CharField(max_length=20)),
                ('district', models.CharField(max_length=20)),
                ('state', models.CharField(max_length=20)),
                ('pincode', models.IntegerField()),
                ('email', models.CharField(max_length=30)),
                ('mobile', models.IntegerField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('uid', models.CharField(max_length=16, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('aadhar', models.IntegerField(max_length=16)),
                ('photo', models.ImageField(upload_to='photos/<django.db.models.fields.CharField>')),
                ('dob', models.DateField()),
                ('gender', models.CharField(max_length=6)),
                ('street', models.CharField(max_length=50)),
                ('district', models.CharField(max_length=20)),
                ('state', models.CharField(max_length=20)),
                ('pincode', models.IntegerField(max_length=6)),
                ('email', models.CharField(max_length=30)),
                ('mobile', models.IntegerField(max_length=10)),
                ('nationality', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='SevaStore',
            fields=[
                ('seva_code', models.CharField(max_length=9, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=16)),
                ('owner_name', models.CharField(max_length=30)),
                ('owner_uid', models.CharField(max_length=16)),
                ('street', models.CharField(max_length=20)),
                ('district', models.CharField(max_length=20)),
                ('state', models.CharField(max_length=20)),
                ('pincode', models.IntegerField()),
                ('email', models.CharField(max_length=20)),
                ('mobile', models.IntegerField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='WorkInfoByOrganisation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(max_length=20)),
                ('join_date', models.DateField()),
                ('resign_date', models.DateField()),
                ('org_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DigiResume.organisation')),
                ('uid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DigiResume.person')),
            ],
        ),
        migrations.CreateModel(
            name='WorkInfoByInstitution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(max_length=20)),
                ('join_date', models.DateField()),
                ('resign_date', models.DateField()),
                ('inst_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DigiResume.institution')),
                ('uid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DigiResume.person')),
            ],
        ),
        migrations.CreateModel(
            name='UnorganisedWorkInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('work_name', models.CharField(max_length=20)),
                ('seva_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DigiResume.sevastore')),
                ('uid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DigiResume.person')),
            ],
        ),
        migrations.CreateModel(
            name='SevaRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=7)),
                ('seva_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DigiResume.sevastore')),
                ('uid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DigiResume.person')),
            ],
        ),
        migrations.CreateModel(
            name='SevaHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now=True)),
                ('action', models.CharField(max_length=50)),
                ('seva_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DigiResume.sevastore')),
                ('uid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DigiResume.person')),
            ],
        ),
        migrations.CreateModel(
            name='RolesByOrganisation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role_name', models.CharField(max_length=20)),
                ('org_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DigiResume.organisation')),
            ],
        ),
        migrations.CreateModel(
            name='RolesByInstitution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role_name', models.CharField(max_length=20)),
                ('inst_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DigiResume.institution')),
            ],
        ),
        migrations.CreateModel(
            name='OrganisationRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=7)),
                ('org_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DigiResume.organisation')),
                ('uid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DigiResume.person')),
            ],
        ),
        migrations.CreateModel(
            name='OrganisationHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_time', models.DateTimeField(auto_now=True)),
                ('action', models.CharField(max_length=50)),
                ('org_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DigiResume.organisation')),
                ('uid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DigiResume.person')),
            ],
        ),
        migrations.CreateModel(
            name='InstitutionRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=7)),
                ('inst_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DigiResume.institution')),
                ('uid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DigiResume.person')),
            ],
        ),
        migrations.CreateModel(
            name='InstitutionHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_time', models.DateTimeField(auto_now=True)),
                ('action', models.CharField(max_length=50)),
                ('inst_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DigiResume.institution')),
                ('uid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DigiResume.person')),
            ],
        ),
        migrations.CreateModel(
            name='EducationInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(max_length=20)),
                ('completion_date', models.DateField()),
                ('grade', models.IntegerField()),
                ('inst_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DigiResume.institution')),
                ('uid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DigiResume.person')),
            ],
        ),
        migrations.CreateModel(
            name='courses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(max_length=20)),
                ('inst_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DigiResume.institution')),
            ],
        ),
    ]
