# Generated by Django 4.0.6 on 2022-08-04 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DigiResume', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='institution',
            name='mobile',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='organisation',
            name='mobile',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='person',
            name='mobile',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='person',
            name='pincode',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='sevastore',
            name='mobile',
            field=models.IntegerField(),
        ),
    ]
