# Generated by Django 4.0.6 on 2022-08-05 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DigiResume', '0004_rename_institutionhistory_institutionactivity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='institution',
            name='inst_name',
            field=models.CharField(default='aaa', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='organisation',
            name='org_name',
            field=models.CharField(default='bbb', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sevastore',
            name='seva_name',
            field=models.CharField(default='ccc', max_length=50),
            preserve_default=False,
        ),
    ]
