# Generated by Django 4.0.6 on 2022-08-07 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DigiResume', '0006_resources_alter_person_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='district',
            field=models.CharField(max_length=40),
        ),
    ]
