# Generated by Django 4.0.6 on 2022-08-08 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DigiResume', '0007_alter_person_district'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='district',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='workinfobyinstitution',
            name='resign_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='workinfobyorganisation',
            name='resign_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
