# Generated by Django 4.0.6 on 2022-08-09 08:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DigiResume', '0009_alter_workinfobyinstitution_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='educationinfo',
            unique_together={('uid', 'inst_code', 'course_name')},
        ),
    ]
