# Generated by Django 4.1 on 2022-08-25 04:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DigiResume', '0010_alter_educationinfo_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='educationinfo',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='workinfobyinstitution',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='workinfobyorganisation',
            unique_together=set(),
        ),
    ]
