# Generated by Django 4.1 on 2022-08-25 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DigiResume', '0011_alter_educationinfo_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rolesbyinstitution',
            name='role_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='rolesbyorganisation',
            name='role_name',
            field=models.CharField(max_length=100),
        ),
    ]
