# Generated by Django 4.1 on 2022-08-25 11:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DigiResume', '0012_alter_person_aadhar'),
        ('DigiResume', '0012_alter_rolesbyinstitution_role_name_and_more'),
    ]

    operations = [
    ]
