# Generated by Django 4.1 on 2022-08-25 08:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DigiResume', '0011_alter_educationinfo_unique_together_and_more'),
        ('DigiResume', '0012_alter_person_aadhar'),
    ]

    operations = [
    ]
