# Generated by Django 4.1 on 2022-08-25 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DigiResume', '0013_merge_20220825_1330'),
    ]

    operations = [
        migrations.AlterField(
            model_name='educationinfo',
            name='course_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='rolesbyorganisation',
            name='role_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='workinfobyinstitution',
            name='role',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='workinfobyorganisation',
            name='role',
            field=models.CharField(max_length=100),
        ),
    ]
