# Generated by Django 4.1 on 2022-08-25 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DigiResume', '0013_merge_20220825_1657'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unorganisedworkinfo',
            name='work_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='workinfobyinstitution',
            name='role',
            field=models.CharField(max_length=100),
        ),
    ]
