# Generated by Django 4.1 on 2022-08-25 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DigiResume', '0014_alter_unorganisedworkinfo_work_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unorganisedworkinfo',
            name='work_name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='workinfobyinstitution',
            name='role',
            field=models.CharField(max_length=200),
        ),
    ]
