# Generated by Django 4.1 on 2022-08-25 13:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DigiResume', '0014_alter_educationinfo_course_name_and_more'),
        ('DigiResume', '0015_alter_unorganisedworkinfo_work_name_and_more'),
    ]

    operations = [
    ]
