# Generated by Django 4.1 on 2022-08-26 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DigiResume', '0016_merge_20220825_1833'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='aadhar',
            field=models.IntegerField(unique=True),
        ),
    ]
