# Generated by Django 4.0.6 on 2022-09-16 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DigiResume', '0017_alter_person_aadhar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='aadhar',
            field=models.IntegerField(),
        ),
    ]
